### ISSUE TITLE
SSL error queue must be clear before calling SSL_get_error.

### ISSUE THREAD

**Issue by birdbrainswagtrain** [uNetworking/uSockets#43] opened 2019-04-04 04:57 UTC
In my application using uWebsockets.js with SSL, all sockets connected to the server will disconnect if one is closed with `WebSocket.end`. I believe I've narrowed the cause down to the two calls to `SSL_get_error` in `ssl.c`. After the first socket is closed, the rest will report incorrect error codes and be disconnected as well.

From the OpenSSL docs:
> SSL_get_error() must be used in the same thread that performed the TLS/SSL I/O operation, and **no other OpenSSL function calls should appear in between**. The current thread's **error queue must be empty** before the TLS/SSL I/O operation is attempted, or SSL_get_error() will not work reliably.

Adding calls to `ERR_clear_error` before `SSL_read`/`SSL_write` fixed the issue for me. I'm submitting an issue rather than a PR because I'm not sure this was the best way to solve the problem, or if the intermediate call to `us_socket_flush` in `us_ssl_socket_write` could cause any issues.

**Comment by alexhultman** [comment] 2019-04-04 05:59
Good report :+1: Will look into this and come back

**Comment by alexhultman** [comment] 2019-08-16 22:46
I cannot reproduce this, you mind creating a reproducing test?

**Comment by birdbrainswagtrain** [comment] 2019-08-20 02:17
I am updating my fork today, and I'm still encountering it. I probably should have mentioned I've only encountered this on linux, and only when the connection is terminated by the server. I'll try to put together a test in the next couple of days.

**Comment by alexhultman** [comment] 2019-08-25 22:56
Yes please do, I run Linux

**Comment by birdbrainswagtrain** [comment] 2019-08-26 04:25
I have created a gist with information, a test program, and the fix I used.

https://gist.github.com/birdbrainswagtrain/149ca5e64729628168855395e494ea8c

**Comment by alexhultman** [comment] 2019-08-26 07:58
Early Christmas, thanks :1st_place_medal:

**Comment by alexhultman** [comment] 2019-08-27 22:06
I cannot reproduce it, but let's merge this anyways. It does make sense to clear it, even if OpenSSL is a complete mess - I checked what that ERR_clear_error() function does and it seems super complex with a bunch of unnecessary garbage.

**Comment by alexhultman** [comment] 2019-08-27 22:26
Calling ERR_clear_error() before SSL_read and SSL_write has a measurable cost,

I reliably get 110k messages/sec without it and 107k with it. That one call is costly.

Tracking WHEN we get an error and clearing it THEN would be a much better solution - we know when functions fail so we can track when we need to clear and when not to.

**Comment by alexhultman** [comment] 2019-11-15 20:31
@birdbrainswagtrain Do you want to try the latest master? I think it should be fixed now

**Closed** 2019-11-19 18:54 UTC
Labels: 0.4.0, bug, enhancement
